apiVersion: apps/v1
kind: Deployment
metadata:
  name: aztier-app
  namespace: aztier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztier-app
  template:
    metadata:
      labels:
        app: aztier-app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: aztier-backend-workload-identity
      containers:
      - name: aztier-frontend
        image: <your-acr-name>.azurecr.io/aztier-frontend:latest  # Replace with your ACR name
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      - name: aztier-backend
        image: <your-acr-name>.azurecr.io/aztier-backend:latest   # Replace with your ACR name
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: aztier-config
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 5000
          periodSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: aztier-frontend
  namespace: aztier
spec:
  selector:
    app: aztier-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: aztier-backend
  namespace: aztier
spec:
  selector:
    app: aztier-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP