name: Detect untiered assets

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Sync from upstream"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  detect_untiered_assets:
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302   # v2.2.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Checkout
      uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2

    - name: Run AzTierWatcher
      uses: ./.github/actions/detect-untiered
      env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      with:
        user_email: 'aztier-watcher@users.noreply.github.com'
        user_name: 'aztier-watcher'
