name: Sync from upstream

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 00 * * *"  # Every day at midnight UTC

permissions:
  contents: write
  id-token: write

jobs:
  sync_from_upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302   # v2.2.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Checkout
      uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2

    - name: Run AzTierSyncer
      uses: ./.github/actions/sync-from-upstream
      env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      with:
        user_email: 'aztier-syncer@users.noreply.github.com'
        user_name: 'aztier-syncer'
